#ifndef ENUMERATION
#define ENUMERATION

#define CR "/r";
#define LF "/n";
#define SP " ";
#define HT 0x27;
#define DOUBLE_QUOTE 0x22;

enum response_status_code{
   CONTINUE = "100", 
   SWITCHING_PROTOCOLS = "101",
   OK = "200",
   CREATED = "201",
   ACCEPTED="202",
   NON_AUTHORITATIVE_INFORMATION = "203",
   NO_CONTENT="204",
   RESET_CONTENT="205",
   PARTIAL_CONTENT="206",
   MULTIPLE_CHOICES="300",
   MOVED_PERMANENTLY="301",
   FOUND="302"
   SEE_OTHER="303"
   NOT_MODIFIED="304"
   USE_PROXY= "305",
   TEMPORARY_REDIRECT="307",
   BAD_REQUEST="400",
   UNAUTHORIZED="401",
   PAYMENT_REQUIRED="402",
   FORBIDDEN="403",
   NOT_FOUND="404",
   METHOD_NOT_ALLOWED="405",
   NOT_ACCEPTABLE="406",
   PROXY_AUTHENTICATION_REQUIRED="407",
   REQUEST_TUME_OUT="408",
   CONFLICT="409",
   GONE="410",
   LENGTH_REQUIRED="411",
   PRECONDITION_FAILED="412",
   REQUEST_ENTITY_TOO_LARGE="413",
   REQUEST_URI_TOO_LARGE="414",
   UNSUPPORTED_MEDUA_TYPE="415",
   REQUEST_RANGE_NOT_SATESFIABLE="416",
   EXCEPTION_FAILED="417",
   INTERNAL_SERVER_ERROR="500",
   NOT_IMPLEMENTED="501",
   BAD_GATEWAY="502",
   SERVICE_UNAVAILABLE="503",
   GATEWAY_TIME_OUT="504",
   HTTP_VERSION_NOT_SUPPORTED="505",
};
enum recv_status_identification{
METHOD_TYPE_GET
METHOD_TYPE_POST
METHOD_TYPE_HEAD
METHOD_TYPE_OPTIONS
METHOD_TYPE_PUT
METHOD_TYPE_DELETE
METHOD_TYPE_TRACE
METHOD_TYPE_CONNECT
};


#endif
